# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModificationMdp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(380, 300)
        MainWindow.setMinimumSize(QtCore.QSize(380, 300))
        MainWindow.setMaximumSize(QtCore.QSize(380, 300))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 20, 371, 221))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.txtConfirmation = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.txtConfirmation.setObjectName("txtConfirmation")
        self.gridLayout_2.addWidget(self.txtConfirmation, 2, 1, 1, 1)
        self.Valider = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.Valider.setObjectName("Valider")
        self.gridLayout_2.addWidget(self.Valider, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.txtAncienMdp = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.txtAncienMdp.setObjectName("txtAncienMdp")
        self.gridLayout_2.addWidget(self.txtAncienMdp, 0, 1, 1, 1)
        self.txtNouveauMdp = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.txtNouveauMdp.setObjectName("txtNouveauMdp")
        self.gridLayout_2.addWidget(self.txtNouveauMdp, 1, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.Annuler = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.Annuler.setObjectName("Annuler")
        self.horizontalLayout_3.addWidget(self.Annuler)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 380, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Nouveau mot de passe"))
        self.Valider.setText(_translate("MainWindow", "Valider"))
        self.label_3.setText(_translate("MainWindow", "Ancien mot de passe"))
        self.label_4.setText(_translate("MainWindow", "Confirmation"))
        self.Annuler.setText(_translate("MainWindow", "Annuler"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
